management:
  security.enabled: false
  context-path: /manage
  add-application-context-header: false

server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8096
#  ssl:
#    key-store: server.keystore
#    key-store-type: JKS
#    key-alias: tomcat
#    enabled: true
#    key-store-password: 123456
  use-forward-headers: true

endpoints:
  shutdown.enabled: false

error:
  whitelabel.enabled: true

spring:
  profiles.active: dev

  application:
    name: vmes-server

  aop:
    auto: true
    proxy-target-class: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: true

  http:
    encoding:
      charset: utf-8
      force: true

  cache:
    type: redis
    cache-names: redisCache
    expire-time-seconds: 300

  resources:
    static-locations: ${ui-path}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 30
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    maxIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 1200000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat,wall

  rabbitmq:
      host: 47.92.1.209
      port: 5672
      username: guest
      password: guest

  mail:
      host: smtp.163.com #smtp服务器主机 smtp.163.com
      username: chen_gang7906@163.com  #邮箱账号 #邮箱账号@163.com
      password: wdmzjcg790412 #第三方登录授权码-必须使用授权码 (第三方授权码:wdmzjcg790412)
      port: 465 #真实使用端口:465
      protocol: smtp #邮件协议 smtp
      default-encoding: UTF-8

      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xy.vmes.**
  typeEnumsPackage: com.xy.vmes.**
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


flowable:
#关闭定时任务JOB
  async-executor-activate: false


