yvan:
  security:
    salt: 12345
    token-expire: 1440  #默认授权时长(一整天)
    token-expire-remember: 43200  #默认授权时长（一个月）
  debug: true
  static_version: v20180504
  static_domain: /static
  upload_domain: /static

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #阿里云MySql
    #外网主机: rm-8vbjns8g515bo16crvo.mysql.zhangbei.rds.aliyuncs.com
    #内网主机: rm-8vbjns8g515bo16cr.mysql.zhangbei.rds.aliyuncs.com

#    url: jdbc:mysql://rm-8vbjns8g515bo16crvo.mysql.zhangbei.rds.aliyuncs.com:3306/deecoop?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#    # url: jdbc:mysql://rm-8vbjns8g515bo16cr.mysql.zhangbei.rds.aliyuncs.com:3306/deecoop?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#    username: vmes
#    password: agrvqL$D

    url: jdbc:mysql://120.27.8.239:3306/deecoop?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    key_prefix: vmes
    host: 120.27.8.239
    port: 6379
    timeout: 0
    expire: 18000

ui-path: file:./vmes-file
